baseURL = "http://www.zjutvis.org/" # The URL of your site
languageCode = "en-gb" # The language you want to display the site in
title = "ZJUTVIS" # The title you want to appear in the address bar
theme = "hugo-developer-portfolio" # The theme, don't change this

googleAnalytics = ""

# Remove this when using normally
# themesDir = "../../" 
# `

#[module]
#  [[module.imports]]
#    path = "github.com/samrobbins85/hugo-developer-portfolio"

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  #URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  URL = "https://zjutvis-1253917436.cos.ap-shanghai.myqcloud.com/cdn/uikit/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  #URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  URL = "https://zjutvis-1253917436.cos.ap-shanghai.myqcloud.com/cdn/uikit/uikit.min.js"
  [[params.plugins.js]]
  #URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"
  URL = "https://zjutvis-1253917436.cos.ap-shanghai.myqcloud.com/cdn/uikit/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "简介"
  URL = "about"
  weight=10

  [[menu.main]]
  name = "科研成果"
  URL = "research"
  weight=2

  [[menu.main]]
  name = "科研论文"
  URL = "publication"
  weight=3

  [[menu.main]]
  name = "成员"
  URL = "members"
  weight=4


[params]
home = "首页"
# Meta data
description = "The website of ZJUTVIS, an academic group, research in VIS, college of computer science, zhejiang university of technology"
author = "ZJUT VIS"


  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "guodao [at] zjut.edu.cn"
  url = "guodao@zjut.edu.cn"
  address = "浙江省杭州市西湖区留和路288号浙江工业大学屏峰校区计算机大楼C516"
  googlemaps = "https://map.baidu.com/search/%E6%B5%99%E6%B1%9F%E7%9C%81%E6%9D%AD%E5%B7%9E%E5%B8%82%E8%A5%BF%E6%B9%96%E5%8C%BA%E7%95%99%E5%92%8C%E8%B7%AF288%E5%8F%B7%E6%B5%99%E6%B1%9F%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6%E5%B1%8F%E5%B3%B0%E6%A0%A1%E5%8C%BA%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%A4%A7%E6%A5%BCc516/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

